version: '3.4'

services:
  coze-discord-proxy:
    image: deanxv/go-geoip:latest
    container_name: go-geoip
    restart: always
    ports:
      - "7099:7099"
    volumes:
      - ./data:/app/go-geoip/data
    environment:
      - API_SECRET=123456  # [可选]修改此行为请求头校验的值（前后端统一）
      - TZ=Asia/Shanghai
      # - CITY_DB_REMOTE_URL=https://xxx.com/GeoIP2-City.mmdb  # [可选]自定义City数据库下载地址
      # - ASN_DB_REMOTE_URL=https://xxx.com/GeoLite2-ASN.mmdb  # [可选]自定义ASN数据库下载地址
      # - CN_DB_REMOTE_URL=https://xxx.com/GeoCN.mmdb  # [可选]自定义CN数据库下载地址